name: rebase-ros-rmw_fastrtps

on:
  schedule:
  - cron: '0 0 * * *'
  # scheduled every midnight
  workflow_dispatch:
  # manual run of the workflow job

jobs:
  rebase-current-branch:
    name: Rebase HEAD with upstream current branch
    runs-on: ubuntu-latest

    steps:
      # Step 1: run a standard checkout action, provided by github (REQUIRED)
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

      # Step 2: rebase action (REQUIRED)
    - name: Rebase current branch to upstream changes
      id: rebase
      run: |
        git remote add ros https://github.com/ros2/rmw_fastrtps.git
        git fetch ros ${GITHUB_REF##*/}
        git config --local user.email "ricardogonzalez@eprosima.com"
        git config --local user.name "richiprosima"
        git rebase ros/${GITHUB_REF##*/}
        if [ "$(git status | grep diverged)" ]; then
          git push -f
        fi;
      shell: bash
